import * as React from "react";

import { storiesOf } from "@storybook/react";
import { action } from "@storybook/addon-actions";
import { linkTo } from "@storybook/addon-links";

import { Button, Welcome } from "@storybook/react/demo";

import SimpleDemo from "./demo-blink-mind-react/SimpleDemo";
import AutoGenerateDepthForTest from "./demo-blink-mind-react/AutoGenerateDepthForTest";
import DemoScrollApi1 from "./demo-scroll-api/Demo1";
import DemoScrollApi2 from "./demo-scroll-api/Demo2";
import DemoScrollApi3 from "./demo-scroll-api/Demo3";

import DragDropDemo1 from "./demo-drag-drop/Demo1";
import DragDropDemo2 from "./demo-drag-drop/Demo2";
import DragDropDemo3 from "./demo-drag-drop/Demo3";
import DragDropDemo4 from "./demo-drag-drop/Demo4";
import DragDropDemo5 from "./demo-drag-drop/Demo5";
import DragDropDemo6 from "./demo-drag-drop/Demo6";
import DragDropDemo7 from "./demo-drag-drop/Demo7";
import DragDropDemo8 from "./demo-drag-drop/Demo8";

let debugNameSpaces = [
  "node:*",
  "model:*",
  "render:*"
  // "-node:LinkWidget"
];

localStorage.debug = debugNameSpaces.join(',');

storiesOf("Welcome", module).add("to Storybook", () => (
  <Welcome showApp={linkTo("Button")} />
));

storiesOf("blink-mind-react-demo", module)
  .add("SimpleDemo", () => <SimpleDemo />)
  .add("AutoGenerateDepthForTest", () => <AutoGenerateDepthForTest />);

storiesOf("drag-scroll-demo", module)
  .add("demo1", () => <DemoScrollApi1 />)
  .add("demo2", () => <DemoScrollApi2 />)
  .add("demo3", () => <DemoScrollApi3 />);

storiesOf("drag-drop", module)
  .add("demo1", () => <DragDropDemo1 />)
  .add("demo2", () => <DragDropDemo2 />)
  .add("demo3", () => <DragDropDemo3 />)
  .add("demo4", () => <DragDropDemo4 />)
  .add("demo5", () => <DragDropDemo5 />)
  .add("demo6", () => <DragDropDemo6 />)
  .add("demo7", () => <DragDropDemo7 />)
  .add("demo8", () => <DragDropDemo8 />);

